cot_cordova:
    build: ./cordova
    net: host
    environment:
        DISPLAY: unix:0 # enable display support
    volumes:
        - ../:/var/application
        - /tmp/.X11-unix:/tmp/.X11-unix # enable display support
    devices:
        - /dev/kvm:/dev/kvm
        - /dev/snd:/dev/snd
        - /dev/net/tun:/dev/net/tun
    working_dir: /var/application
    tty: true
